<?php
/**
 * @copyright Copyright 2003-2022 Zen Cart Development Team
 * @copyright Portions Copyright 2003 osCommerce
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 * @version $Id: Scott C Wilson 2022 Jan 11 New in v1.5.8-alpha $
*/

$define = [
    'HEADING_TITLE' => 'Types de Produits',
    'HEADING_TITLE_LAYOUT' => 'Options de mise en page du type de produit : ',
    'TABLE_HEADING_PRODUCT_TYPES' => 'Types de produits',
    'TABLE_HEADING_PRODUCT_TYPES_ALLOW_ADD_TO_CART' => 'Ajouter<br>au panier',
    'TEXT_HEADING_NEW_PRODUCT_TYPE' => 'Nouveau type de produit',
    'TEXT_HEADING_EDIT_PRODUCT_TYPE' => 'Éditer le type de produit',
    'TEXT_HEADING_DELETE_PRODUCT_TYPE' => 'Supprimer le type de produit',
    'TEXT_PRODUCT_TYPES' => 'Types de produit :',
    'TEXT_PRODUCT_TYPES_HANDLER' => 'Page de gestion :',
    'TEXT_PRODUCT_TYPES_ALLOW_ADD_CART' => 'Ce produit peut être ajouté au panier :',
    'TEXT_MASTER_TYPE' => 'Ce type de produit doit être considéré comme un sous-type de ',
    'TEXT_NEW_INTRO' => 'Veuillez insérer les informations requises pour le nouveau fabricant',
    'TEXT_PRODUCT_TYPES_NAME' => 'Nom du type de produit :',
    'TEXT_PRODUCT_TYPES_IMAGE' => 'Image par défaut du type de produit :',
    'TEXT_DELETE_INTRO' => 'Êtes-vous certain(e) de vouloir supprimer ce type de produit ?',
    'TEXT_DELETE_PRODUCTS' => 'Supprimer les produits de ce type de produit ? (en incluant les avis, les promotions et les produits attendus)',
    'TEXT_DELETE_WARNING_PRODUCTS' => '<b>ATTENTION :</b> Il y a %s produit(s) encore associé(s) à ce type de produit !',
    'IMAGE_LAYOUT' => 'Paramètres de mise en page',
// Table product_types, translation for field type_name
    'PRODUCT_TYPE_NAME_FOR_HANDLER_PRODUCT' => 'Produit - Général',
    'PRODUCT_TYPE_NAME_FOR_HANDLER_PRODUCT_MUSIC' => 'Produit - Musique',
    'PRODUCT_TYPE_NAME_FOR_HANDLER_DOCUMENT_GENERAL' => 'Document - Général',
    'PRODUCT_TYPE_NAME_FOR_HANDLER_DOCUMENT_PRODUCT' => 'Document - Produit',
    'PRODUCT_TYPE_NAME_FOR_HANDLER_PRODUCT_FREE_SHIPPING' => 'Produit - Envoi Gratuit',
// Table product_type_layout, translation for field configuration_title and configuration_description
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_MODEL' => 'Afficher le modèle',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_MODEL' => 'Afficher le numéro de modèle dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_WEIGHT' => 'Afficher le poids',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_WEIGHT' => 'Afficher le poids dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_WEIGHT_ATTRIBUTES' => 'Afficher le poids des options',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_WEIGHT_ATTRIBUTES' => 'Afficher le poids des options dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_MANUFACTURER' => 'Afficher le fabricant',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_MANUFACTURER' => 'Afficher le nom du fabricant dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_IN_CART_QTY' => 'Afficher la quantité dans le panier',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_IN_CART_QTY' => 'Afficher la quantité qctuellement dans le panier dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_QUANTITY' => 'Afficher la quantité en stock',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_QUANTITY' => 'Afficher la quantité en stock dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_REVIEWS_COUNT' => 'Afficher le nombre de revues',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_REVIEWS_COUNT' => 'Afficher le nombre de revues dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_REVIEWS' => 'Afficher le bouton des revues',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_REVIEWS' => 'Afficher le bouton des revues dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_DATE_AVAILABLE' => 'Afficher la date de disponibilité',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_DATE_AVAILABLE' => 'Afficher la date de disponibilité dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_DATE_ADDED' => 'Afficher la date d\'ajout',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_DATE_ADDED' => 'Afficher la date d\'ajout dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_URL' => 'Afficher l\'URL du produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_URL' => 'Afficher l\'URL dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_ADDITIONAL_IMAGES' => 'Afficher des images supplémentaires',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_ADDITIONAL_IMAGES' => 'Afficher des images supplémentaires dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_STARTING_AT' => 'Afficher le texte « À partir de » devant le prix',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_STARTING_AT' => 'Afficher le texte « À partir de » pour les produits avec des options dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Statut de l\'image des produits à Livraison gratuite - Catalogue',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Afficher l\'image/le texte de la livraison gratuite dans le catalogue ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_TAX_CLASS_ID' => 'Classe de taxe par défaut pour le prix des produits  - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_TAX_CLASS_ID' => 'Quel doit être l\'ID par défaut de la classe de taxe pour le prix des produits lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_PRODUCTS_VIRTUAL' => 'Statut par défaut des produits virtuels - Ignorer l\'adresse de livraison - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_PRODUCTS_VIRTUAL' => 'Le statut du produit virtuel par défaut doit-il être activé lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Statut par défaut des produits à livraison gratuite - Règles d\'expédition normales - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Quel doit être le statut de livraison gratuite par défaut lors de l\'ajout de nouveaux produits ?<br>Oui, livraison toujours gratuite<br>Non, livraison gratuite toujours désactivée<br>Produits/téléchargements en promotion nécessitent une expédition',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_MODEL' => 'Afficher le modèle',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_MODEL' => 'Afficher le numéro de modèle dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_WEIGHT' => 'Afficher le poids',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_WEIGHT' => 'Afficher le poids dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_WEIGHT_ATTRIBUTES' => 'Afficher le poids des options',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_WEIGHT_ATTRIBUTES' => 'Afficher le poids des options dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_ARTIST' => 'Afficher l\'artiste',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_ARTIST' => 'Afficher le nom de l\'artiste dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_GENRE' => 'Afficher le genre musical',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_GENRE' => 'Afficher le genre musical dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_RECORD_COMPANY' => 'Afficher la maison de disques',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_RECORD_COMPANY' => 'Afficher la maison de disques dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_IN_CART_QTY' => 'Afficher la quantité dans le panier',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_IN_CART_QTY' => 'Afficher la quantité qctuellement dans le panier dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_QUANTITY' => 'Afficher la quantité en stock',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_QUANTITY' => 'Afficher la quantité en stock dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_REVIEWS_COUNT' => 'Afficher le nombre de revues',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_REVIEWS_COUNT' => 'Afficher le nombre de revues dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_REVIEWS' => 'Afficher le bouton des revues',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_REVIEWS' => 'Afficher le bouton des revues dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_DATE_AVAILABLE' => 'Afficher la date de disponibilité',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_DATE_AVAILABLE' => 'Afficher la date de disponibilité dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_DATE_ADDED' => 'Afficher la date d\'ajout',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_DATE_ADDED' => 'Afficher la date d\'ajout dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_STARTING_AT' => 'Afficher le texte « À partir de » devant le prix',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_STARTING_AT' => 'Afficher le texte « À partir de » pour les produits avec des options dans les informations de produit 0= off 1= on\'Afficher le texte « À partir de » pour les produits avec des attributs dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_ADDITIONAL_IMAGES' => 'Afficher des images supplémentaires',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_ADDITIONAL_IMAGES' => 'Afficher des images supplémentaires dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Statut de l\'image des produits à Livraison gratuite - Catalogue',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Afficher l\'image/le texte de la livraison gratuite dans le catalogue ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_TAX_CLASS_ID' => 'Classe de taxe par défaut pour le prix des produits  - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_TAX_CLASS_ID' => 'Quel doit être l\'ID par défaut de la classe de taxe pour le prix des produits lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_VIRTUAL' => 'Statut par défaut des produits virtuels - Ignorer l\'adresse de livraison - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_VIRTUAL' => 'Le statut du produit virtuel par défaut doit-il être activé lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Statut par défaut des produits à livraison gratuite - Règles d\'expédition normales - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Quel doit être le statut de livraison gratuite par défaut lors de l\'ajout de nouveaux produits ?<br>Oui, livraison toujours gratuite<br>Non, livraison gratuite toujours désactivée<br>Produits/téléchargements en promotion nécessitent une expédition',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_REVIEWS_COUNT' => 'Afficher le nombre de revues',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_REVIEWS_COUNT' => 'Afficher le nombre de revues dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_REVIEWS' => 'Afficher le bouton des revues',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_REVIEWS' => 'Afficher le bouton des revues dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_DATE_AVAILABLE' => 'Afficher la date de disponibilité',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_DATE_AVAILABLE' => 'Afficher la date de disponibilité dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_DATE_ADDED' => 'Afficher la date d\'ajout',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_DATE_ADDED' => 'Afficher la date d\'ajout dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_URL' => 'Afficher l\'URL du produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_URL' => 'Afficher l\'URL dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_ADDITIONAL_IMAGES' => 'Afficher des images supplémentaires',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_ADDITIONAL_IMAGES' => 'Afficher des images supplémentaires dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_MODEL' => 'Afficher le modèle',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_MODEL' => 'Afficher le numéro de modèle dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_WEIGHT' => 'Afficher le poids',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_WEIGHT' => 'Afficher le poids dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_WEIGHT_ATTRIBUTES' => 'Afficher le poids des options',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_WEIGHT_ATTRIBUTES' => 'Afficher le poids des options dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_MANUFACTURER' => 'Afficher le fabricant',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_MANUFACTURER' => 'Afficher le nom du fabricant dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_IN_CART_QTY' => 'Afficher la quantité dans le panier',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_IN_CART_QTY' => 'Afficher la quantité qctuellement dans le panier dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_QUANTITY' => 'Afficher la quantité en stock',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_QUANTITY' => 'Afficher la quantité en stock dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_REVIEWS_COUNT' => 'Afficher le nombre de revues',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_REVIEWS_COUNT' => 'Afficher le nombre de revues dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_REVIEWS' => 'Afficher le bouton des revues',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_REVIEWS' => 'Afficher le bouton des revues dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_DATE_AVAILABLE' => 'Afficher la date de disponibilité',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_DATE_AVAILABLE' => 'Afficher la date de disponibilité dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_DATE_ADDED' => 'Afficher la date d\'ajout',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_DATE_ADDED' => 'Afficher la date d\'ajout dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_URL' => 'Afficher l\'URL du produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_URL' => 'Afficher l\'URL dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ADDITIONAL_IMAGES' => 'Afficher des images supplémentaires',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ADDITIONAL_IMAGES' => 'Afficher des images supplémentaires dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_STARTING_AT' => 'Afficher le texte « À partir de » devant le prix',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_STARTING_AT' => 'Afficher le texte « À partir de » pour les produits avec des options dans les informations de produit 0= off 1= on\'Afficher le texte « À partir de » pour les produits avec des attributs dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Statut de l\'image des produits à Livraison gratuite - Catalogue',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Afficher l\'image/le texte de la livraison gratuite dans le catalogue ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_TAX_CLASS_ID' => 'Classe de taxe par défaut pour le prix des produits  - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_TAX_CLASS_ID' => 'Quel doit être l\'ID par défaut de la classe de taxe pour le prix des produits lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_VIRTUAL' => 'Statut par défaut des produits virtuels - Ignorer l\'adresse de livraison - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_VIRTUAL' => 'Le statut du produit virtuel par défaut doit-il être activé lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Statut par défaut des produits à livraison gratuite - Règles d\'expédition normales - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Quel doit être le statut de livraison gratuite par défaut lors de l\'ajout de nouveaux produits ?<br>Oui, livraison toujours gratuite<br>Non, livraison gratuite toujours désactivée<br>Produits/téléchargements en promotion nécessitent une expédition',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_MODEL' => 'Afficher le modèle',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_MODEL' => 'Afficher le numéro de modèle dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_WEIGHT' => 'Afficher le poids',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_WEIGHT' => 'Afficher le poids dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_WEIGHT_ATTRIBUTES' => 'Afficher le poids des options',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_WEIGHT_ATTRIBUTES' => 'Afficher le poids des options dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_MANUFACTURER' => 'Afficher le fabricant',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_MANUFACTURER' => 'Afficher le nom du fabricant dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_IN_CART_QTY' => 'Afficher la quantité dans le panier',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_IN_CART_QTY' => 'Afficher la quantité qctuellement dans le panier dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_QUANTITY' => 'Afficher la quantité en stock',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_QUANTITY' => 'Afficher la quantité en stock dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_REVIEWS_COUNT' => 'Afficher le nombre de revues',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_REVIEWS_COUNT' => 'Afficher le nombre de revues dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_REVIEWS' => 'Afficher le bouton des revues',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_REVIEWS' => 'Afficher le bouton des revues dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_DATE_AVAILABLE' => 'Afficher la date de disponibilité',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_DATE_AVAILABLE' => 'Afficher la date de disponibilité dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_DATE_ADDED' => 'Afficher la date d\'ajout',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_DATE_ADDED' => 'Afficher la date d\'ajout dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_URL' => 'Afficher l\'URL du produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_URL' => 'Afficher l\'URL dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ADDITIONAL_IMAGES' => 'Afficher des images supplémentaires',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ADDITIONAL_IMAGES' => 'Afficher des images supplémentaires dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_STARTING_AT' => 'Afficher le texte « À partir de » devant le prix',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_STARTING_AT' => 'Afficher le texte « À partir de » pour les produits avec des options dans les informations de produit 0= off 1= on\'Afficher le texte « À partir de » pour les produits avec des attributs dans les informations de produit 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Statut de l\'image des produits à Livraison gratuite - Catalogue',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Afficher l\'image/le texte de la livraison gratuite dans le catalogue ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_TAX_CLASS_ID' => 'Classe de taxe par défaut pour le prix des produits  - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_TAX_CLASS_ID' => 'Quel doit être l\'ID par défaut de la classe de taxe pour le prix des produits lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_VIRTUAL' => 'Statut par défaut des produits virtuels - Ignorer l\'adresse de livraison - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_VIRTUAL' => 'Le statut du produit virtuel par défaut doit-il être activé lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Statut par défaut des produits à livraison gratuite - Règles d\'expédition normales - Lors de l\'ajout de nouveaux produits ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Quel doit être le statut de livraison gratuite par défaut lors de l\'ajout de nouveaux produits ?<br>Oui, livraison toujours gratuite<br>Non, livraison gratuite toujours désactivée<br>Produits/téléchargements en promotion nécessitent une expédition',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le nom de produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le nom du produit dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_METATAGS_TITLE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser un texte supplémentaire',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_METATAGS_TITLE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le texte supplémentaire du titre dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_METATAGS_MODEL_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le numéro de modèle du produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_METATAGS_MODEL_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le modèle du produit dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_METATAGS_PRICE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le prix du produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_METATAGS_PRICE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le prix du produit dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser SITE_TAGLINE',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher la constante « SITE_TAGLINE » dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le nom de produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le nom du produit dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_TITLE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser un texte supplémentaire',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_TITLE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le titre du produit dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_MODEL_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le numéro de modèle du produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_MODEL_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le modèle du produit dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_PRICE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le prix du produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_PRICE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le prix du produit dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser SITE_TAGLINE',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher la constante « SITE_TAGLINE » dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_TITLE_STATUS' => 'Balise &lt;titre&gt; de la page Document - par défaut : utiliser le titre du document',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_TITLE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le titre du document dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Balise &lt;titre&gt; de la page Document - par défaut : utiliser le nom du document',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le nom du document dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le slogan du document',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le slogan du document dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_TITLE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le titre du document',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_TITLE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le titre du document dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le nom du document',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le nom du document dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_MODEL_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le numéro de modèle du document',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_MODEL_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le modèle de document dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_PRICE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le prix du document',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_PRICE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le prix du document dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le slogan du document',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le slogan du document dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_TITLE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le nom de produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_TITLE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le nom du produit dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser un texte supplémentaire',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le texte supplémentaire du titre dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_MODEL_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le numéro de modèle du produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_MODEL_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le modèle du produit dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_PRICE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser le prix du produit',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_PRICE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher le prix du produit dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Balise &lt;titre&gt; de la page produit - par défaut : utiliser SITE_TAGLINE',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Paramètre par défaut pour un nouveau produit (peut être modifié par produit).<br>Afficher la constante « SITE_TAGLINE » dans la balise du &lt;titre&gt; de la page.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DISPLAY_ONLY' => 'Option produit « Affichage uniquement » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DISPLAY_ONLY' => 'L\'option de produit « afficher uniquement »<br>Utiliser uniquement à des fins d\'affichage<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTE_IS_FREE' => 'Option produit « Gratuit » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTE_IS_FREE' => 'L\'option de produit « Gratuit »<br>L\'option est gratuite quand le produit est gratuit<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DEFAULT' => 'Option produit « Par Défaut » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DEFAULT' => 'L\'option de produit « Par Défaut »<br>L\'option est sélectionnée par défaut<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DISCOUNTED' => 'Option produit « En Solde » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DISCOUNTED' => 'L\'option de produit « En Solde »<br>Appliquer les réductions définies dans produits En Vedette/Promotion<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'Option produit « Inclus dans le prix » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'L\'option de produit « Inclus dans le prix »<br>Inclus dans le prix de base quand le prix par options est utilisé<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTES_REQUIRED' => 'Option produit « Requis » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTES_REQUIRED' => 'L\'option de produit « Requis »<br>Option requise pour le texte<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_PRICE_PREFIX' => 'Option produit « Correction de prix » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_PRICE_PREFIX' => 'L\'option de produit « Correction de prix »<br>Correction de prix à ajouter par défaut au prix de l\'option<br>Vide, + ou -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'Option produit « Correction de poids » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'L\'option de produit « Correction de poids »<br>Correction de poids par défaut<br>Vide, + ou -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DISPLAY_ONLY' => 'Option de musique « Affichage uniquement » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DISPLAY_ONLY' => 'L\'option de musique « afficher uniquement »<br>Utiliser uniquement à des fins d\'affichage<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTE_IS_FREE' => 'Option de musique « Gratuit » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTE_IS_FREE' => 'L\'option de musique « Gratuit »<br>L\'option est gratuite quand le produit est gratuit<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DEFAULT' => 'Option de musique « Par Défaut » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DEFAULT' => 'L\'option de musique « Par Défaut »<br>L\'option est sélectionnée par défaut<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DISCOUNTED' => 'Option de musique « En Solde » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DISCOUNTED' => 'L\'option de musique « En Solde »<br>Appliquer les réductions définies dans produits En Vedette/Promotion<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'Option de musique « Inclus dans le prix » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'L\'option de musique « Inclus dans le prix »<br>Inclus dans le prix de base quand le prix par options est utilisé<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_REQUIRED' => 'Option de musique « Requis » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_REQUIRED' => 'L\'option de musique « Requis »<br>Option requise pour le texte<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_PRICE_PREFIX' => 'Option de musique « Correction de prix » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_PRICE_PREFIX' => 'L\'option de musique « Correction de prix »<br>Correction de prix à ajouter par défaut au prix de l\'option<br>Vide, + ou -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'Option de musique « Correction de poids » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'L\'option de musique « Correction de poids »<br>Correction de poids par défaut<br>Vide, + ou -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DISPLAY_ONLY' => 'Option de document général « Affichage uniquement » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DISPLAY_ONLY' => 'L\'option de document général « afficher uniquement »<br>Utiliser uniquement à des fins d\'affichage<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTE_IS_FREE' => 'Option de document général « Gratuit » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTE_IS_FREE' => 'L\'option de document général « Gratuit »<br>L\'option est gratuite quand le produit est gratuit<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DEFAULT' => 'Option de document général « Par Défaut » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DEFAULT' => 'L\'option de document général « Par Défaut »<br>L\'option est sélectionnée par défaut<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DISCOUNTED' => 'Option de document général « En Solde » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DISCOUNTED' => 'L\'option de document général « En Solde »<br>Appliquer les réductions définies dans produits En Vedette/Promotion<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'Option de document général « Inclus dans le prix » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'L\'option de document général « Inclus dans le prix »<br>Inclus dans le prix de base quand le prix par options est utilisé<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_REQUIRED' => 'Option de document général « Requis » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_REQUIRED' => 'L\'option de document général « Requis »<br>Option requise pour le texte<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_PRICE_PREFIX' => 'Option de document général « Correction de prix » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_PRICE_PREFIX' => 'L\'option de document général « Correction de prix »<br>Correction de prix à ajouter par défaut au prix de l\'option<br>Vide, + ou -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'Option de document général « Correction de poids » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'L\'option de document général « Correction de poids »<br>Correction de poids par défaut<br>Vide, + ou -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DISPLAY_ONLY' => 'Option de document - produit « Affichage uniquement » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DISPLAY_ONLY' => 'L\'option de document - produit « afficher uniquement »<br>Utiliser uniquement à des fins d\'affichage<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTE_IS_FREE' => 'Option de document - produit « Gratuit » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTE_IS_FREE' => 'L\'option de document - produit « Gratuit »<br>L\'option est gratuite quand le produit est gratuit<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DEFAULT' => 'Option de document - produit « Par Défaut » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DEFAULT' => 'L\'option de document - produit « Par Défaut »<br>L\'option est sélectionnée par défaut<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DISCOUNTED' => 'Option de document - produit « En Solde » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DISCOUNTED' => 'L\'option de document - produit « En Solde »<br>Appliquer les réductions définies dans produits En Vedette/Promotion<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'Option de document - produit « Inclus dans le prix » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'L\'option de document - produit « Inclus dans le prix »<br>Inclus dans le prix de base quand le prix par options est utilisé<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_REQUIRED' => 'Option de document - produit « Requis » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_REQUIRED' => 'L\'option de document - produit « Requis »<br>Option requise pour le texte<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_PRICE_PREFIX' => 'Option de document - produit « Correction de prix » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_PRICE_PREFIX' => 'L\'option de document - produit « Correction de prix »<br>Correction de prix à ajouter par défaut au prix de l\'option<br>Vide, + ou -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'Option de document - produit « Correction de poids » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'L\'option de document - produit « Correction de poids »<br>Correction de poids par défaut<br>Vide, + ou -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DISPLAY_ONLY' => 'Option des produits à envoi gratuit « Affichage uniquement » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DISPLAY_ONLY' => 'L\'option des produits à envoi gratuit « afficher uniquement »<br>Utiliser uniquement à des fins d\'affichage<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTE_IS_FREE' => 'Option des produits à envoi gratuit « Gratuit » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTE_IS_FREE' => 'L\'option des produits à envoi gratuit « Gratuit »<br>L\'option est gratuite quand le produit est gratuit<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DEFAULT' => 'Option des produits à envoi gratuit « Par Défaut » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DEFAULT' => 'L\'option des produits à envoi gratuit « Par Défaut »<br>L\'option est sélectionnée par défaut<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DISCOUNTED' => 'Option des produits à envoi gratuit « En Solde » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DISCOUNTED' => 'L\'option des produits à envoi gratuit « En Solde »<br>Appliquer les réductions définies dans produits En Vedette/Promotion<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'Option des produits à envoi gratuit « Inclus dans le prix » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'L\'option des produits à envoi gratuit « Inclus dans le prix »<br>Inclus dans le prix de base quand le prix par options est utilisé<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_REQUIRED' => 'Option des produits à envoi gratuit « Requis » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_REQUIRED' => 'L\'option des produits à envoi gratuit « Requis »<br>Option requise pour le texte<br>0= Non 1= Oui',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRICE_PREFIX' => 'Option des produits à envoi gratuit « Correction de prix » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRICE_PREFIX' => 'L\'option des produits à envoi gratuit « Correction de prix »<br>Correction de prix à ajouter par défaut au prix de l\'option<br>Vide, + ou -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'Option des produits à envoi gratuit « Correction de poids » - Par défaut',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'L\'option des produits à envoi gratuit « Correction de poids »<br>Correction de poids par défaut<br>Vide, + ou -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_ASK_A_QUESTION' => 'Afficher le bouton « Poser une question » ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_ASK_A_QUESTION' => 'Afficher le bouton « Poser une question » dans les informations de produit? (0 = False, 1 = True)',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_ASK_A_QUESTION' => 'Afficher le bouton « Poser une question » ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_ASK_A_QUESTION' => 'Afficher le bouton « Poser une question » dans les informations de produit? (0 = False, 1 = True)',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_ASK_A_QUESTION' => 'Afficher le bouton « Poser une question » ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_ASK_A_QUESTION' => 'Afficher le bouton « Poser une question » dans les informations de produit? (0 = False, 1 = True)',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ASK_A_QUESTION' => 'Afficher le bouton « Poser une question » ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ASK_A_QUESTION' => 'Afficher le bouton « Poser une question » dans les informations de produit? (0 = False, 1 = True)',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ASK_A_QUESTION' => 'Afficher le bouton « Poser une question » ?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ASK_A_QUESTION' => 'Afficher le bouton « Poser une question » dans les informations de produit? (0 = False, 1 = True)',
];

return $define;
