<?php
$define = [
    'MODULE_PAYMENT_PAYPAL_TEXT_ADMIN_TITLE' => 'Paiements PayPal Standard',
    'MODULE_PAYMENT_PAYPAL_TEXT_ADMIN_TITLE_NONUSA' => 'Paiements PayPal Standard sur site Web - IPN',
    'MODULE_PAYMENT_PAYPAL_TEXT_CATALOG_TITLE' => 'PayPal',
    'MODULE_PAYMENT_PAYPAL_MARK_BUTTON_IMG' => 'https://www.paypal.com/en_US/i/logo/PayPal_mark_37x23.gif',
    'MODULE_PAYMENT_PAYPAL_MARK_BUTTON_ALT' => 'Encaisser avec PayPal',
    'MODULE_PAYMENT_PAYPAL_ACCEPTANCE_MARK_TEXT' => 'Gangnez du temps. Encaissez en toute sécurité. <br />Payez sans dévoiler vos informations financières.',
    'MODULE_PAYMENT_PAYPAL_PURCHASE_DESCRIPTION_TITLE' => 'Tous les articles dans votre panier (voir les détails dans la boutique et sur votre reçu de la boutique).',
    'MODULE_PAYMENT_PAYPAL_PURCHASE_DESCRIPTION_ITEMNUM' => STORE_NAME . ' Achat',
    'MODULES_PAYMENT_PAYPALSTD_LINEITEM_TEXT_ONETIME_CHARGES_PREFIX' => 'Frais uniques se rapportant ',
    'MODULES_PAYMENT_PAYPALSTD_LINEITEM_TEXT_SURCHARGES_SHORT' => 'Surtaxes',
    'MODULES_PAYMENT_PAYPALSTD_LINEITEM_TEXT_SURCHARGES_LONG' => 'Frais de manutention et autres charges applicables',
    'MODULES_PAYMENT_PAYPALSTD_LINEITEM_TEXT_DISCOUNTS_SHORT' => 'Remises',
    'MODULES_PAYMENT_PAYPALSTD_LINEITEM_TEXT_DISCOUNTS_LONG' => 'Rabais appliqués, incluant les bons de réduction, chèques-cadeaux, etc',
    'MODULES_PAYMENT_PAYPALSTD_NOT_RECOMMENDED' => 'Veuillez noter que ce module n\'est plus recommandé. Voir <a href="https://docs.zen-cart.com/user/payment/paypal_standard/" target="_blank" rel="noreferrer noopener">cette page</a> pour une explication.',
    'MODULE_PAYMENT_PAYPAL_ENTRY_FIRST_NAME' => 'Prénom : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_LAST_NAME' => 'Nom : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_BUSINESS_NAME' => 'Nom de l\'entreprise : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_ADDRESS_NAME' => 'Adresse nom : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_ADDRESS_STREET' => 'Adresse : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_ADDRESS_CITY' => 'Ville : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_ADDRESS_STATE' => 'Région/Département : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_ADDRESS_ZIP' => 'Code Postal : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_ADDRESS_COUNTRY' => 'Pays : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_EMAIL_ADDRESS' => 'E-mail du payeur : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_EBAY_ID' => ' ID# Ebay : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_PAYER_ID' => 'ID# payeur : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_PAYER_STATUS' => 'Statut du payeur : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_ADDRESS_STATUS' => 'Statut de l\'adresse : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_PAYMENT_TYPE' => 'Type de paiement : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_PAYMENT_STATUS' => 'Statut du paiement : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_PENDING_REASON' => 'Motif de mise en attente : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_INVOICE' => 'Facture : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_PAYMENT_DATE' => 'Date de paiement : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_CURRENCY' => 'Devise : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_GROSS_AMOUNT' => 'Montant brut : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_PAYMENT_FEE' => 'Commission : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_EXCHANGE_RATE' => 'Taux de change : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_CART_ITEMS' => 'Articles dans panier : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_TXN_TYPE' => 'Type transaction : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_TXN_ID' => 'ID# transaction : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_PARENT_TXN_ID' => 'ID# transaction parent : ',
    'MODULE_PAYMENT_PAYPAL_ENTRY_COMMENTS' => 'Commentaires système : ',
// bof constant configuration titles and descriptions for payment module paypal
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_STATUS' => 'Activer le module « PayPal »',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_STATUS' => 'Souhaitez-vous accepter les paiements PayPal ?',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_BUSINESS_ID' => 'ID d\'entreprise',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_BUSINESS_ID' => 'Adresse e-mail principale de votre compte PayPal.<br>REMARQUE : elle doit correspondre <strong>EXACTEMENT</strong> à l\'adresse e-mail principale indiquée dans les paramètres de votre compte PayPal. Elle est <strong>sensible à la casse</strong>. Veuillez donc vérifier vos préférences de profil PayPal sur paypal.com et assurez-vous de saisir EXACTEMENT la même adresse e-mail principale ici.',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_CURRENCY' => 'Devise de transaction',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_CURRENCY' => 'Dans quelle devise la commande doit-elle être envoyée à PayPal ? <br>REMARQUE : si une devise non prise en charge est envoyée à PayPal, elle sera automatiquement convertie en USD.',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_ZONE' => 'Zone de paiement',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_ZONE' => 'Si une zone est sélectionnée, activez uniquement ce mode de paiement pour cette zone.',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_PROCESSING_STATUS_ID' => 'Définir le statut de notification en attente',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_PROCESSING_STATUS_ID' => 'Définissez le statut des commandes qui ne sont pas encore terminées sur cette valeur.<br>(« En attente » recommandé)',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_ORDER_STATUS_ID' => 'Définir le statut de la commande',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_ORDER_STATUS_ID' => 'Définissez le statut des commandes dont le paiement a été effectué sur cette valeur.<br>(« En cours » recommandé)',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_REFUND_ORDER_STATUS_ID' => 'Définir le statut des commandes remboursées',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_REFUND_ORDER_STATUS_ID' => 'Définissez le statut des commandes remboursées sur cette valeur :<br>(« En attente » recommandé)',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_SORT_ORDER' => 'Ordre de tri',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_SORT_ORDER' => 'Ordre d\'affichage.',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_ADDRESS_OVERRIDE' => 'Remplacement d\'adresse',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_ADDRESS_OVERRIDE' => 'Si la valeur est définie sur 1, l\'adresse de livraison du client sélectionnée dans Zen Cart remplacera le carnet d\'adresses PayPal du client. Le client verra son adresse dans Zen Cart, mais NE pourra PAS la modifier sur PayPal.<br>(Une adresse non valide sera traitée par PayPal comme non fournie, ou override=0)<br>0=Aucune substitution<br>1=L\'adresse ZC remplace les choix d\'adresse PayPal',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_ADDRESS_REQUIRED' => 'Exigences relatives à l’adresse de livraison ?',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_ADDRESS_REQUIRED' => 'L\'adresse de livraison des acheteurs. Si la valeur est définie sur 0, votre client sera invité à inclure une adresse de livraison. Si la valeur est définie sur 1, votre client ne sera pas invité à fournir une adresse de livraison. Si la valeur est définie sur 2, votre client devra fournir une adresse de livraison.<br>0=Proposé<br>1=Non demandé<br>2=Obligatoire<br><br><strong>REMARQUE : si vous permettez à vos clients de saisir leur propre adresse de livraison, ASSUREZ-VOUS de vérifier manuellement les détails de confirmation PayPal afin de vous assurer que l\'adresse est correcte lors de la préparation des commandes.Lors de l\'utilisation de PayPal Payments Standard (IPN), Zen Cart ne sait pas si une adresse de livraison alternative sur PayPal a été choisie à la place de celle saisie lors de la commande.</strong>',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_DETAILED_CART' => 'Articles détaillés dans le panier',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_DETAILED_CART' => 'Voulez-vous communiquer les détails des articles à PayPal ? Si cette option est définie sur True, les détails des articles seront partagés avec PayPal si aucune remise ne s\'applique et si les taxes et les frais d\'expédition sont simples. Sinon, un résumé global du panier sera envoyé.',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_PAGE_STYLE' => 'Style de page',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_PAGE_STYLE' => 'Définit le style de page de paiement personnalisé pour les pages de paiement. La valeur de page_style est la même que le nom du style de page que vous avez choisi lors de l\'ajout ou de la modification du style de page. Vous pouvez ajouter et modifier des styles de page de paiement personnalisés à partir du sous-onglet Profil de l\'onglet Mon compte sur le site PayPal. Si vous souhaitez toujours faire référence à votre style principal, définissez-le sur « primary ». Si vous souhaitez faire référence au style de page PayPal par défaut, définissez-le sur « paypal ».',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_HANDLER' => 'En direct ou en Sandbox',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_HANDLER' => '<strong>Live : </strong> Utilisé pour traiter les transactions en direct<br><strong>Sandbox : </strong>Pour les développeurs et les tests',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_PDTTOKEN' => 'Jeton PDT (transfert de données de paiement)',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_PDTTOKEN' => 'Saisissez ici la valeur de votre jeton PDT afin d\'activer les transactions immédiatement après leur traitement (si elles passent la validation).',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_IPN_DEBUG' => 'Mode débogage',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_IPN_DEBUG' => 'Activer la journalisation de débogage ? <br>REMARQUE : cela peut VRAIMENT encombrer votre boîte de réception et utiliser de l\'espace disque !<br>La journalisation va dans le dossier /logs.<br>Le courrier électronique est envoyé à l\'adresse du propriétaire du magasin.<br>L\'option de courrier électronique n\'est PAS recommandée.<br><strong>Laissez OFF pour un fonctionnement normal.</strong>',
    'CFGTITLE_MODULE_PAYMENT_PAYPAL_DEBUG_EMAIL_ADDRESS' => 'Adresse Email de débogage',
    'CFGDESC_MODULE_PAYMENT_PAYPAL_DEBUG_EMAIL_ADDRESS' => 'L\'adresse e-mail à utiliser pour le débogage PayPal',
// eof constant configuration titles and descriptions for payment module paypal
];

if (IS_ADMIN_FLAG === true) {
    $define['MODULE_PAYMENT_PAYPAL_TEXT_DESCRIPTION'] = '<strong>PayPal Payments Standard</strong> (Service PayPal plus ancien, moins fiable que Express Checkout)<br><a href="https://www.paypal.com" rel="noreferrer noopener" target="_blank">Gérez votre compte PayPal.</a><br><br><b>Instructions de configuration :</b><br>1. <a href="https://www.zen-cart.com/partners/paypal-std" rel="noopener" target="_blank">Créez votre compte PayPal - cliquez ici.</a><br>2. Dans votre compte PayPal, sous "Profil",<ul><li>définissez votre URL de <strong>Préférences de notification de paiement instantanée</strong> à :<br><pre>' . str_replace('index.php?main_page=index', 'ipn_main_handler.php', zen_catalog_href_link(FILENAME_DEFAULT)) . '</pre><br>(Si une autre URL valide est déjà saisie, vous pouvez la laisser telle quelle.)<br><span class="alert">Assurez-vous que la case à cocher pour activer l\'IPN est cochée !</span><br><br></li><li>dans les <strong>Préférences de paiement du site Web</strong>, définissez votre <strong>URL de retour automatique</strong> sur :<br><pre>' . zen_catalog_href_link(FILENAME_CHECKOUT_PROCESS, '', 'SSL', false) . '</pre></li>' . (defined('MODULE_PAYMENT_PAYPALSTD_STATUS') ? '' : '<li>... et cliquez sur "installer" ci-dessus pour activer le support PayPal Standard... et "modifier" pour indiquer à Zen Cart vos paramètres PayPal.</li>') . '</ul><hr><strong>Requis :</strong><br><br>*<strong>Compte PayPal</strong> (<a href="https://www.zen-cart.com/partners/paypal-std" rel="noopener" target="_blank">cliquez pour installer/configurer</a>)<br>*<strong>CURL avec SSL</strong> est fortement recommandé<br>*<strong>Le port 80 (et le port 443 si SSL est activé)</strong> est utilisé pour la communication <strong>*bidirectionnelle*</strong> avec la passerelle, et doit donc être ouvert sur le routeur/pare-feu de votre hôte.<br>*<strong>Les paramètres</strong> de votre compte PayPal doivent être configurés comme décrit ci-dessus.';
} else {
    $define['MODULE_PAYMENT_PAYPAL_TEXT_DESCRIPTION'] = '<strong>PayPal</strong>';
}
$define['MODULE_PAYMENT_PAYPAL_TEXT_CATALOG_LOGO'] = '<img src="' . $define['MODULE_PAYMENT_PAYPAL_MARK_BUTTON_IMG'] . '" alt="' . $define['MODULE_PAYMENT_PAYPAL_MARK_BUTTON_ALT'] . '" title="' . $define['MODULE_PAYMENT_PAYPAL_MARK_BUTTON_ALT'] . '"> &nbsp;' .
        '<span class="smallText">' . $define['MODULE_PAYMENT_PAYPAL_ACCEPTANCE_MARK_TEXT'] . '</span>';

return $define;
