<?php
$define = [
    'MODULE_ORDER_TOTAL_COD_TITLE' => 'COD Fee',
    'MODULE_ORDER_TOTAL_COD_DESCRIPTION' => 'COD Fee',
    'TEXT_INFO_COD_FEES' => '<strong>Note:</strong> COD fees may apply',
// bof constant configuration titles and descriptions for order total module ot_cod_fee
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_STATUS' => 'Display COD',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_STATUS' => 'Do you want this module to display?',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_SORT_ORDER' => 'Sort Order',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_SORT_ORDER' => 'Sort order of display.',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_FLAT' => 'COD Fee for FLAT',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_FLAT' => 'FLAT: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_FREE' => 'COD Fee for Free Shipping by default',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_FREE' => 'Free by default: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_FREESHIPPER' => 'COD Fee for Free Shipping Module - (freeshipper)',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_FREESHIPPER' => 'Free Module: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_FREEOPTIONS' => 'COD Fee for Free-Options Shipping Module - (freeoptions)',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_FREEOPTIONS' => 'Free+Options: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_PERWEIGHTUNIT' => 'COD Fee for Per Weight Unit Shipping Module - (perweightunit)',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_PERWEIGHTUNIT' => 'Per Weight Unit: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_ITEM' => 'COD Fee for ITEM',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_ITEM' => 'ITEM: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_TABLE' => 'COD Fee for TABLE',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_TABLE' => 'TABLE: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_UPS' => 'COD Fee for UPS',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_UPS' => 'UPS: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_USPS' => 'COD Fee for USPS',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_USPS' => 'USPS: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_ZONES' => 'COD Fee for ZONES',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_ZONES' => 'ZONES: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_AP' => 'COD Fee for Austrian Post',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_AP' => 'Austrian Post: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_DP' => 'COD Fee for German Post',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_DP' => 'German Post: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_SERVICEPAKKE' => 'COD Fee for Servicepakke',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_SERVICEPAKKE' => 'Servicepakke: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_FEE_FEDEX' => 'COD Fee for FedEx',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_FEE_FEDEX' => 'FedEx: &lt;Country code&gt;:&lt;COD price&gt;, .... 00 as country code applies for all countries. If country code is 00, it must be the last statement. If no 00:9.99 appears, COD shipping in foreign countries is not calculated (not possible)',
    'CFGTITLE_MODULE_ORDER_TOTAL_COD_TAX_CLASS' => 'Tax Class',
    'CFGDESC_MODULE_ORDER_TOTAL_COD_TAX_CLASS' => 'Use the following tax class on the COD fee.',
// eof constant configuration titles and descriptions for order total module ot_cod_fee
];

return $define;
