<?php
/**
 * @copyright Copyright 2003-2022 Zen Cart Development Team
 * @copyright Portions Copyright 2003 osCommerce
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 * @version $Id: Scott C Wilson 2022 Jan 11 New in v1.5.8-alpha $
*/

$define = [
    'HEADING_TITLE' => 'Product Types',
    'HEADING_TITLE_LAYOUT' => 'Product Type Info Page Layout options :: ',
    'TABLE_HEADING_PRODUCT_TYPES' => 'Product Types',
    'TABLE_HEADING_PRODUCT_TYPES_ALLOW_ADD_TO_CART' => 'Add<br>to Cart',
    'TEXT_HEADING_NEW_PRODUCT_TYPE' => 'New Product Type',
    'TEXT_HEADING_EDIT_PRODUCT_TYPE' => 'Edit Product Type',
    'TEXT_HEADING_DELETE_PRODUCT_TYPE' => 'Delete Product Type',
    'TEXT_PRODUCT_TYPES' => 'Product Types:',
    'TEXT_PRODUCT_TYPES_HANDLER' => 'Handler Page:',
    'TEXT_PRODUCT_TYPES_ALLOW_ADD_CART' => 'This Product can be added to cart:',
    'TEXT_MASTER_TYPE' => 'This product type should be considered a sub-type of ',
    'TEXT_NEW_INTRO' => 'Please fill out the following information for the new manufacturer',
    'TEXT_PRODUCT_TYPES_NAME' => 'Product Type Name:',
    'TEXT_PRODUCT_TYPES_IMAGE' => 'Product Type Default Image:',
    'TEXT_DELETE_INTRO' => 'Are you sure you want to delete this product type?',
    'TEXT_DELETE_PRODUCTS' => 'Delete products from this product type? (including product reviews, products on special, upcoming products)',
    'TEXT_DELETE_WARNING_PRODUCTS' => '<b>WARNING:</b> There are %s products still linked to this product type!',
    'IMAGE_LAYOUT' => 'Layout Settings',
// Table product_types, translation for field type_name
    'PRODUCT_TYPE_NAME_FOR_HANDLER_PRODUCT' => 'Product - General',
    'PRODUCT_TYPE_NAME_FOR_HANDLER_PRODUCT_MUSIC' => 'Product - Music',
    'PRODUCT_TYPE_NAME_FOR_HANDLER_DOCUMENT_GENERAL' => 'Document - General',
    'PRODUCT_TYPE_NAME_FOR_HANDLER_DOCUMENT_PRODUCT' => 'Document - Product',
    'PRODUCT_TYPE_NAME_FOR_HANDLER_PRODUCT_FREE_SHIPPING' => 'Product - Free Shipping',
// Table product_type_layout, translation for field configuration_title and configuration_description
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_MODEL' => 'Show Model Number',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_MODEL' => 'Display Model Number on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_WEIGHT' => 'Show Weight',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_WEIGHT' => 'Display Weight on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_WEIGHT_ATTRIBUTES' => 'Show Attribute Weight',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_WEIGHT_ATTRIBUTES' => 'Display Attribute Weight on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_MANUFACTURER' => 'Show Manufacturer',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_MANUFACTURER' => 'Display Manufacturer Name on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_IN_CART_QTY' => 'Show Quantity in Shopping Cart',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_IN_CART_QTY' => 'Display Quantity in Current Shopping Cart on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_QUANTITY' => 'Show Quantity in Stock',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_QUANTITY' => 'Display Quantity in Stock on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_REVIEWS_COUNT' => 'Show Product Reviews Count',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_REVIEWS_COUNT' => 'Display Product Reviews Count on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_REVIEWS' => 'Show Product Reviews Button',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_REVIEWS' => 'Display Product Reviews Button on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_DATE_AVAILABLE' => 'Show Date Available',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_DATE_AVAILABLE' => 'Display Date Available on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_DATE_ADDED' => 'Show Date Added',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_DATE_ADDED' => 'Display Date Added on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_URL' => 'Show Product URL',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_URL' => 'Display URL on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_ADDITIONAL_IMAGES' => 'Show Product Additional Images',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_ADDITIONAL_IMAGES' => 'Display Additional Images on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_STARTING_AT' => 'Show Starting At text on Price',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_STARTING_AT' => 'Display Starting At text on products with attributes Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Product Free Shipping Image Status - Catalog',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Show the Free Shipping image/text in the catalog?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_TAX_CLASS_ID' => 'Product Price Tax Class Default - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_TAX_CLASS_ID' => 'What should the Product Price Tax Class Default ID be when adding new products?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_PRODUCTS_VIRTUAL' => 'Product Virtual Default Status - Skip Shipping Address - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_PRODUCTS_VIRTUAL' => 'Default Virtual Product status to be ON when adding new products?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Product Free Shipping Default Status - Normal Shipping Rules - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'What should the Default Free Shipping status be when adding new products?<br />Yes, Always Free Shipping ON<br />No, Always Free Shipping OFF<br />Special, Product/Download Requires Shipping',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_MODEL' => 'Show Model Number',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_MODEL' => 'Display Model Number on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_WEIGHT' => 'Show Weight',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_WEIGHT' => 'Display Weight on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_WEIGHT_ATTRIBUTES' => 'Show Attribute Weight',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_WEIGHT_ATTRIBUTES' => 'Display Attribute Weight on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_ARTIST' => 'Show Artist',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_ARTIST' => 'Display Artists Name on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_GENRE' => 'Show Music Genre',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_GENRE' => 'Display Music Genre on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_RECORD_COMPANY' => 'Show Record Company',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_RECORD_COMPANY' => 'Display Record Company on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_IN_CART_QTY' => 'Show Quantity in Shopping Cart',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_IN_CART_QTY' => 'Display Quantity in Current Shopping Cart on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_QUANTITY' => 'Show Quantity in Stock',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_QUANTITY' => 'Display Quantity in Stock on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_REVIEWS_COUNT' => 'Show Product Reviews Count',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_REVIEWS_COUNT' => 'Display Product Reviews Count on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_REVIEWS' => 'Show Product Reviews Button',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_REVIEWS' => 'Display Product Reviews Button on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_DATE_AVAILABLE' => 'Show Date Available',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_DATE_AVAILABLE' => 'Display Date Available on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_DATE_ADDED' => 'Show Date Added',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_DATE_ADDED' => 'Display Date Added on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_STARTING_AT' => 'Show Starting At text on Price',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_STARTING_AT' => 'Display Starting At text on products with attributes Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_ADDITIONAL_IMAGES' => 'Show Product Additional Images',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_ADDITIONAL_IMAGES' => 'Display Additional Images on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Product Free Shipping Image Status - Catalog',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Show the Free Shipping image/text in the catalog?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_TAX_CLASS_ID' => 'Product Price Tax Class Default - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_TAX_CLASS_ID' => 'What should the Product Price Tax Class Default ID be when adding new products?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_VIRTUAL' => 'Product Virtual Default Status - Skip Shipping Address - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_VIRTUAL' => 'Default Virtual Product status to be ON when adding new products?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Product Free Shipping Default Status - Normal Shipping Rules - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'What should the Default Free Shipping status be when adding new products?<br />Yes, Always Free Shipping ON<br />No, Always Free Shipping OFF<br />Special, Product/Download Requires Shipping',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_REVIEWS_COUNT' => 'Show Product Reviews Count',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_REVIEWS_COUNT' => 'Display Product Reviews Count on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_REVIEWS' => 'Show Product Reviews Button',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_REVIEWS' => 'Display Product Reviews Button on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_DATE_AVAILABLE' => 'Show Date Available',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_DATE_AVAILABLE' => 'Display Date Available on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_DATE_ADDED' => 'Show Date Added',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_DATE_ADDED' => 'Display Date Added on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_URL' => 'Show Product URL',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_URL' => 'Display URL on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_ADDITIONAL_IMAGES' => 'Show Product Additional Images',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_ADDITIONAL_IMAGES' => 'Display Additional Images on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_MODEL' => 'Show Model Number',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_MODEL' => 'Display Model Number on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_WEIGHT' => 'Show Weight',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_WEIGHT' => 'Display Weight on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_WEIGHT_ATTRIBUTES' => 'Show Attribute Weight',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_WEIGHT_ATTRIBUTES' => 'Display Attribute Weight on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_MANUFACTURER' => 'Show Manufacturer',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_MANUFACTURER' => 'Display Manufacturer Name on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_IN_CART_QTY' => 'Show Quantity in Shopping Cart',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_IN_CART_QTY' => 'Display Quantity in Current Shopping Cart on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_QUANTITY' => 'Show Quantity in Stock',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_QUANTITY' => 'Display Quantity in Stock on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_REVIEWS_COUNT' => 'Show Product Reviews Count',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_REVIEWS_COUNT' => 'Display Product Reviews Count on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_REVIEWS' => 'Show Product Reviews Button',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_REVIEWS' => 'Display Product Reviews Button on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_DATE_AVAILABLE' => 'Show Date Available',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_DATE_AVAILABLE' => 'Display Date Available on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_DATE_ADDED' => 'Show Date Added',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_DATE_ADDED' => 'Display Date Added on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_URL' => 'Show Product URL',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_URL' => 'Display URL on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ADDITIONAL_IMAGES' => 'Show Product Additional Images',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ADDITIONAL_IMAGES' => 'Display Additional Images on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_STARTING_AT' => 'Show Starting At text on Price',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_STARTING_AT' => 'Display Starting At text on products with attributes Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Product Free Shipping Image Status - Catalog',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Show the Free Shipping image/text in the catalog?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_TAX_CLASS_ID' => 'Product Price Tax Class Default - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_TAX_CLASS_ID' => 'What should the Product Price Tax Class Default ID be when adding new products?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_VIRTUAL' => 'Product Virtual Default Status - Skip Shipping Address - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_VIRTUAL' => 'Default Virtual Product status to be ON when adding new products?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Product Free Shipping Default Status - Normal Shipping Rules - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'What should the Default Free Shipping status be when adding new products?<br />Yes, Always Free Shipping ON<br />No, Always Free Shipping OFF<br />Special, Product/Download Requires Shipping',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_MODEL' => 'Show Model Number',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_MODEL' => 'Display Model Number on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_WEIGHT' => 'Show Weight',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_WEIGHT' => 'Display Weight on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_WEIGHT_ATTRIBUTES' => 'Show Attribute Weight',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_WEIGHT_ATTRIBUTES' => 'Display Attribute Weight on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_MANUFACTURER' => 'Show Manufacturer',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_MANUFACTURER' => 'Display Manufacturer Name on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_IN_CART_QTY' => 'Show Quantity in Shopping Cart',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_IN_CART_QTY' => 'Display Quantity in Current Shopping Cart on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_QUANTITY' => 'Show Quantity in Stock',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_QUANTITY' => 'Display Quantity in Stock on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_REVIEWS_COUNT' => 'Show Product Reviews Count',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_REVIEWS_COUNT' => 'Display Product Reviews Count on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_REVIEWS' => 'Show Product Reviews Button',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_REVIEWS' => 'Display Product Reviews Button on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_DATE_AVAILABLE' => 'Show Date Available',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_DATE_AVAILABLE' => 'Display Date Available on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_DATE_ADDED' => 'Show Date Added',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_DATE_ADDED' => 'Display Date Added on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_URL' => 'Show Product URL',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_URL' => 'Display URL on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ADDITIONAL_IMAGES' => 'Show Product Additional Images',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ADDITIONAL_IMAGES' => 'Display Additional Images on Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_STARTING_AT' => 'Show Starting At text on Price',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_STARTING_AT' => 'Display Starting At text on products with attributes Product Info 0= off 1= on',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Product Free Shipping Image Status - Catalog',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ALWAYS_FREE_SHIPPING_IMAGE_SWITCH' => 'Show the Free Shipping image/text in the catalog?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_TAX_CLASS_ID' => 'Product Price Tax Class Default - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_TAX_CLASS_ID' => 'What should the Product Price Tax Class Default ID be when adding new products?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_VIRTUAL' => 'Product Virtual Default Status - Skip Shipping Address - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_VIRTUAL' => 'Default Virtual Product status to be ON when adding new products?',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'Product Free Shipping Default Status - Normal Shipping Rules - When adding new products?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_IS_ALWAYS_FREE_SHIPPING' => 'What should the Default Free Shipping status be when adding new products?<br />Yes, Always Free Shipping ON<br />No, Always Free Shipping OFF<br />Special, Product/Download Requires Shipping',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Product page &lt;title&gt; tag - default: use Product Name',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Product Name in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_METATAGS_TITLE_STATUS' => 'Product page &lt;title&gt; tag - default: use Title Additional Text',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_METATAGS_TITLE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Title Additional text in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_METATAGS_MODEL_STATUS' => 'Product page &lt;title&gt; tag - default: use Product Model',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_METATAGS_MODEL_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Product Model in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_METATAGS_PRICE_STATUS' => 'Product page &lt;title&gt; tag - default: use Product Price',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_METATAGS_PRICE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Product Price in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Product page &lt;title&gt; tag - default: use SITE_TAGLINE',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the defined constant "SITE_TAGLINE" in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Product page &lt;title&gt; tag - default: use Product Name',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Product Name in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_TITLE_STATUS' => 'Product page &lt;title&gt; tag - default: use Title Additional Text',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_TITLE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Product Title in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_MODEL_STATUS' => 'Product page &lt;title&gt; tag - default: use Product Model',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_MODEL_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Product Model in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_PRICE_STATUS' => 'Product page &lt;title&gt; tag - default: use Product Price',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_PRICE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Product Price in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Product page &lt;title&gt; tag - default: use SITE_TAGLINE',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the defined constant "SITE_TAGLINE" in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_TITLE_STATUS' => 'Document page &lt;title&gt; tag - default: use Document Title',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_TITLE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Document  Title in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Document page &lt;title&gt; tag - default: use Document Name',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Document  Name in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Product page &lt;title&gt; tag - default: use Document Tagline',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Document  Tagline in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_TITLE_STATUS' => 'Product page &lt;title&gt; tag - default: use Document Title',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_TITLE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Document  Title in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Product page &lt;title&gt; tag - default: use Document Name',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Document  Name in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_MODEL_STATUS' => 'Product page &lt;title&gt; tag - default: use Document Model',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_MODEL_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Document  Model in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_PRICE_STATUS' => 'Product page &lt;title&gt; tag - default: use Document Price',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_PRICE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Document  Price in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Product page &lt;title&gt; tag - default: use Document Tagline',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Document  Tagline in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_TITLE_STATUS' => 'Product page &lt;title&gt; tag - default: use Product Name',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_TITLE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Product Name in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Product page &lt;title&gt; tag - default: use Title Additional Text',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_PRODUCTS_NAME_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Title Additional text in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_MODEL_STATUS' => 'Product page &lt;title&gt; tag - default: use Product Model',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_MODEL_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Product Model in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_PRICE_STATUS' => 'Product page &lt;title&gt; tag - default: use Product Price',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_PRICE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the Product Price in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Product page &lt;title&gt; tag - default: use SITE_TAGLINE',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_METATAGS_TITLE_TAGLINE_STATUS' => 'Default setting for a new product (can be modified per product).<br>Show the defined constant "SITE_TAGLINE" in the page &lt;title&gt; tag.',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DISPLAY_ONLY' => 'PRODUCT Attribute is Display Only - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DISPLAY_ONLY' => 'PRODUCT Attribute is Display Only<br />Used For Display Purposes Only<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTE_IS_FREE' => 'PRODUCT Attribute is Free - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTE_IS_FREE' => 'PRODUCT Attribute is Free<br />Attribute is Free When Product is Free<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DEFAULT' => 'PRODUCT Attribute is Default - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DEFAULT' => 'PRODUCT Attribute is Default<br />Default Attribute to be Marked Selected<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DISCOUNTED' => 'PRODUCT Attribute is Discounted - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTES_DISCOUNTED' => 'PRODUCT Attribute is Discounted<br />Apply Discounts Used by Product Special/Sale<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'PRODUCT Attribute is Included in Base Price - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'PRODUCT Attribute is Included in Base Price<br />Include in Base Price When Priced by Attributes<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_ATTRIBUTES_REQUIRED' => 'PRODUCT Attribute is Required - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_ATTRIBUTES_REQUIRED' => 'PRODUCT Attribute is Required<br />Attribute Required for Text<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_PRICE_PREFIX' => 'PRODUCT Attribute Price Prefix - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_PRICE_PREFIX' => 'PRODUCT Attribute Price Prefix<br />Default Attribute Price Prefix for Adding<br />Blank, + or -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'PRODUCT Attribute Weight Prefix - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'PRODUCT Attribute Weight Prefix<br />Default Attribute Weight Prefix<br />Blank, + or -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DISPLAY_ONLY' => 'MUSIC Attribute is Display Only - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DISPLAY_ONLY' => 'MUSIC Attribute is Display Only<br />Used For Display Purposes Only<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTE_IS_FREE' => 'MUSIC Attribute is Free - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTE_IS_FREE' => 'MUSIC Attribute is Free<br />Attribute is Free When Product is Free<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DEFAULT' => 'MUSIC Attribute is Default - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DEFAULT' => 'MUSIC Attribute is Default<br />Default Attribute to be Marked Selected<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DISCOUNTED' => 'MUSIC Attribute is Discounted - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_DISCOUNTED' => 'MUSIC Attribute is Discounted<br />Apply Discounts Used by Product Special/Sale<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'MUSIC Attribute is Included in Base Price - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'MUSIC Attribute is Included in Base Price<br />Include in Base Price When Priced by Attributes<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_REQUIRED' => 'MUSIC Attribute is Required - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_ATTRIBUTES_REQUIRED' => 'MUSIC Attribute is Required<br />Attribute Required for Text<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_PRICE_PREFIX' => 'MUSIC Attribute Price Prefix - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_PRICE_PREFIX' => 'MUSIC Attribute Price Prefix<br />Default Attribute Price Prefix for Adding<br />Blank, + or -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'MUSIC Attribute Weight Prefix - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_MUSIC_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'MUSIC Attribute Weight Prefix<br />Default Attribute Weight Prefix<br />Blank, + or -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DISPLAY_ONLY' => 'DOCUMENT GENERAL Attribute is Display Only - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DISPLAY_ONLY' => 'DOCUMENT GENERAL Attribute is Display Only<br />Used For Display Purposes Only<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTE_IS_FREE' => 'DOCUMENT GENERAL Attribute is Free - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTE_IS_FREE' => 'DOCUMENT GENERAL Attribute is Free<br />Attribute is Free When Product is Free<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DEFAULT' => 'DOCUMENT GENERAL Attribute is Default - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DEFAULT' => 'DOCUMENT GENERAL Attribute is Default<br />Default Attribute to be Marked Selected<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DISCOUNTED' => 'DOCUMENT GENERAL Attribute is Discounted - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_DISCOUNTED' => 'DOCUMENT GENERAL Attribute is Discounted<br />Apply Discounts Used by Product Special/Sale<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'DOCUMENT GENERAL Attribute is Included in Base Price - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'DOCUMENT GENERAL Attribute is Included in Base Price<br />Include in Base Price When Priced by Attributes<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_REQUIRED' => 'DOCUMENT GENERAL Attribute is Required - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_ATTRIBUTES_REQUIRED' => 'DOCUMENT GENERAL Attribute is Required<br />Attribute Required for Text<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_PRICE_PREFIX' => 'DOCUMENT GENERAL Attribute Price Prefix - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_PRICE_PREFIX' => 'DOCUMENT GENERAL Attribute Price Prefix<br />Default Attribute Price Prefix for Adding<br />Blank, + or -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_GENERAL_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'DOCUMENT GENERAL Attribute Weight Prefix - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_GENERAL_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'DOCUMENT GENERAL Attribute Weight Prefix<br />Default Attribute Weight Prefix<br />Blank, + or -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DISPLAY_ONLY' => 'DOCUMENT PRODUCT Attribute is Display Only - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DISPLAY_ONLY' => 'DOCUMENT PRODUCT Attribute is Display Only<br />Used For Display Purposes Only<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTE_IS_FREE' => 'DOCUMENT PRODUCT Attribute is Free - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTE_IS_FREE' => 'DOCUMENT PRODUCT Attribute is Free<br />Attribute is Free When Product is Free<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DEFAULT' => 'DOCUMENT PRODUCT Attribute is Default - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DEFAULT' => 'DOCUMENT PRODUCT Attribute is Default<br />Default Attribute to be Marked Selected<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DISCOUNTED' => 'DOCUMENT PRODUCT Attribute is Discounted - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_DISCOUNTED' => 'DOCUMENT PRODUCT Attribute is Discounted<br />Apply Discounts Used by Product Special/Sale<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'DOCUMENT PRODUCT Attribute is Included in Base Price - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'DOCUMENT PRODUCT Attribute is Included in Base Price<br />Include in Base Price When Priced by Attributes<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_REQUIRED' => 'DOCUMENT PRODUCT Attribute is Required - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_ATTRIBUTES_REQUIRED' => 'DOCUMENT PRODUCT Attribute is Required<br />Attribute Required for Text<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_PRICE_PREFIX' => 'DOCUMENT PRODUCT Attribute Price Prefix - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_PRICE_PREFIX' => 'DOCUMENT PRODUCT Attribute Price Prefix<br />Default Attribute Price Prefix for Adding<br />Blank, + or -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'DOCUMENT PRODUCT Attribute Weight Prefix - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_DOCUMENT_PRODUCT_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'DOCUMENT PRODUCT Attribute Weight Prefix<br />Default Attribute Weight Prefix<br />Blank, + or -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DISPLAY_ONLY' => 'PRODUCT FREE SHIPPING Attribute is Display Only - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DISPLAY_ONLY' => 'PRODUCT FREE SHIPPING Attribute is Display Only<br />Used For Display Purposes Only<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTE_IS_FREE' => 'PRODUCT FREE SHIPPING Attribute is Free - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTE_IS_FREE' => 'PRODUCT FREE SHIPPING Attribute is Free<br />Attribute is Free When Product is Free<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DEFAULT' => 'PRODUCT FREE SHIPPING Attribute is Default - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DEFAULT' => 'PRODUCT FREE SHIPPING Attribute is Default<br />Default Attribute to be Marked Selected<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DISCOUNTED' => 'PRODUCT FREE SHIPPING Attribute is Discounted - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_DISCOUNTED' => 'PRODUCT FREE SHIPPING Attribute is Discounted<br />Apply Discounts Used by Product Special/Sale<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'PRODUCT FREE SHIPPING Attribute is Included in Base Price - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_PRICE_BASE_INCLUDED' => 'PRODUCT FREE SHIPPING Attribute is Included in Base Price<br />Include in Base Price When Priced by Attributes<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_REQUIRED' => 'PRODUCT FREE SHIPPING Attribute is Required - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_ATTRIBUTES_REQUIRED' => 'PRODUCT FREE SHIPPING Attribute is Required<br />Attribute Required for Text<br />0= No 1= Yes',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRICE_PREFIX' => 'PRODUCT FREE SHIPPING Attribute Price Prefix - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRICE_PREFIX' => 'PRODUCT FREE SHIPPING Attribute Price Prefix<br />Default Attribute Price Prefix for Adding<br />Blank, + or -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'PRODUCT FREE SHIPPING Attribute Weight Prefix - Default',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_DEFAULT_PRODUCT_FREE_SHIPPING_PRODUCTS_ATTRIBUTES_WEIGHT_PREFIX' => 'PRODUCT FREE SHIPPING Attribute Weight Prefix<br />Default Attribute Weight Prefix<br />Blank, + or -',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_INFO_ASK_A_QUESTION' => 'Show \"Ask a Question\" button?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_INFO_ASK_A_QUESTION' => 'Display the \"Ask a Question\" button on product Info pages? (0 = False, 1 = True)',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_MUSIC_INFO_ASK_A_QUESTION' => 'Show \"Ask a Question\" button?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_MUSIC_INFO_ASK_A_QUESTION' => 'Display the \"Ask a Question\" button on product Info pages? (0 = False, 1 = True)',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_GENERAL_INFO_ASK_A_QUESTION' => 'Show \"Ask a Question\" button?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_GENERAL_INFO_ASK_A_QUESTION' => 'Display the \"Ask a Question\" button on product Info pages? (0 = False, 1 = True)',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ASK_A_QUESTION' => 'Show \"Ask a Question\" button?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_DOCUMENT_PRODUCT_INFO_ASK_A_QUESTION' => 'Display the \"Ask a Question\" button on product Info pages? (0 = False, 1 = True)',
    'PRODUCT_TYPE_LAYOUT_TITLE_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ASK_A_QUESTION' => 'Show \"Ask a Question\" button?',
    'PRODUCT_TYPE_LAYOUT_DESC_FOR_SHOW_PRODUCT_FREE_SHIPPING_INFO_ASK_A_QUESTION' => 'Display the \"Ask a Question\" button on product Info pages? (0 = False, 1 = True)',
];

return $define;
